### ISSUE TITLE
How to extend this starter?

### ISSUE THREAD

**Issue by kamilDevguru** [LekoArts/gatsby-starter-portfolio-cara#113] opened 2019-08-04 21:47 UTC
There is no pages folder in `src` folder in this starter.
Even I tried to add new pages directory and about page and file and `about` page was not working which was supposed to work.
any idea?

**Comment by LekoArts** [comment] 2019-08-05 06:32
I can't reproduce this: https://codesandbox.io/s/cara-with-pages-fyfvi
It's working fine for me.

This starter uses a theme which creates the index page with `createPage`. That's why there is no `src/pages` folder. You can also include the theme into an existing site of yours and change the basePath if necessary.

Closing this issue as answered but please comment if you need further help. Thanks!

**Closed by LekoArts** 2019-08-05 06:32 UTC
